<Project>
  <PropertyGroup>
    <Version>1.3.0-beta.7</Version>
    <InformationalVersion>1.3.0-beta.7</InformationalVersion>
    <RepositoryCommit>cebd0e55130735689e62971d4acce02d5ab2af54</RepositoryCommit>
    <Authors>Marcel Kummerow</Authors>
    <Company>CScharf</Company>
    <Product>Kiln</Product>
    <Copyright>Copyright © 2026 Marcel Kummerow</Copyright>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RepositoryUrl>https://github.com/PepperPix/Kiln</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.StaticAnalysis" Version="10.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
