namespace Kiln.Services;

using System.Collections.ObjectModel;
using System.Diagnostics;
using Kiln.Models;

public sealed class SiteBuilder(
    IContentReader contentReader,
    ITemplateRenderer templateRenderer,
    IPermalinkGenerator permalinkGenerator,
    ISiteConfigLoader configLoader) : ISiteBuilder
{
    public async Task<BuildResult> BuildAsync(string projectPath, bool includeDrafts = false, CancellationToken ct = default)
    {
        var stopwatch = Stopwatch.StartNew();
        var warnings = new Collection<string>();
        var errors = new Collection<string>();

        // Load configuration
        var config = configLoader.Load(projectPath);
        var outputDir = Path.Combine(projectPath, config.OutputDir);
        var themePath = Path.Combine(projectPath, config.ThemesDir, config.Theme);

        if (!Directory.Exists(themePath))
        {
            errors.Add($"Theme directory not found: {themePath}");
            return MakeResult(0, 0, 0, stopwatch.Elapsed, outputDir, warnings, errors);
        }

        // Read all collections and assign URLs
        var allItems = new List<ContentItem>();
        foreach (var collection in config.Collections.Values)
        {
            var items = contentReader.ReadCollection(collection, projectPath);
            foreach (var item in items)
            {
                item.Url = permalinkGenerator.Generate(item, collection);
                item.OutputPath = ToOutputPath(item.Url);
                collection.Items.Add(item);
            }

            allItems.AddRange(items);
        }

        // Permalink collision check
        var collisionGroups = allItems.GroupBy(i => i.Url.OriginalString).Where(g => g.Count() > 1);
        foreach (var collision in collisionGroups)
        {
            var sources = string.Join(", ", collision.Select(i => i.RelativePath));
            errors.Add($"Permalink collision — '{collision.Key}' is generated by: {sources}");
        }

        if (errors.Count > 0)
            return MakeResult(allItems.Count, 0, 0, stopwatch.Elapsed, outputDir, warnings, errors);

        // Clean and create output directory
        if (Directory.Exists(outputDir))
            Directory.Delete(outputDir, recursive: true);
        Directory.CreateDirectory(outputDir);

        var rendered = 0;
        var skippedDrafts = 0;

        foreach (var item in allItems)
        {
            ct.ThrowIfCancellationRequested();

            if (item.Draft && !includeDrafts)
            {
                skippedDrafts++;
                continue;
            }

            try
            {
                var html = templateRenderer.Render(item, config, themePath);
                var outputPath = Path.Combine(outputDir, item.OutputPath);
                var outputDirectory = Path.GetDirectoryName(outputPath)!;

                Directory.CreateDirectory(outputDirectory);
                await File.WriteAllTextAsync(outputPath, html, ct).ConfigureAwait(false);
                rendered++;
            }
#pragma warning disable CA1031 // Intentional: one file error should not abort the entire build
            catch (Exception ex)
#pragma warning restore CA1031
            {
                errors.Add($"Error rendering '{item.RelativePath}': {ex.Message}");
            }
        }

        // Copy static assets from theme → _site/assets/ (lowest priority)
        var assetsOutputDir = Path.Combine(outputDir, "assets");
        var themeStaticDir = Path.Combine(themePath, "static");
        if (Directory.Exists(themeStaticDir))
            CopyDirectory(themeStaticDir, assetsOutputDir);

        // Copy static assets from site → _site/assets/ (overrides theme, warns on collision)
        var siteStaticDir = Path.Combine(projectPath, "static");
        if (Directory.Exists(siteStaticDir))
            CopyDirectoryWithCollisionWarning(siteStaticDir, assetsOutputDir, config.Theme, warnings);

        // Copy co-located assets from Page Bundles → _site/assets/content/<collection>/<slug>/
        foreach (var item in allItems.Where(static i => i.AssetDirectory is not null))
        {
            var destDir = Path.Combine(assetsOutputDir, "content", item.Collection.Name, item.Slug);
            CopyNonMarkdownFiles(item.AssetDirectory!, destDir);
        }

        stopwatch.Stop();
        return MakeResult(allItems.Count, rendered, skippedDrafts, stopwatch.Elapsed, outputDir, warnings, errors);
    }

    private static string ToOutputPath(Uri url)
    {
        // /blog/hello-world/ → blog/hello-world/index.html
        var normalized = url.OriginalString.Trim('/');
        return string.IsNullOrEmpty(normalized)
            ? "index.html"
            : Path.Combine(normalized, "index.html");
    }

    private static BuildResult MakeResult(int total, int rendered, int skipped, TimeSpan duration, string outputDir, Collection<string> warnings, Collection<string> errors)
    {
        return new BuildResult
        {
            TotalFiles = total,
            RenderedFiles = rendered,
            SkippedDrafts = skipped,
            Duration = duration,
            OutputDirectory = outputDir,
            Warnings = warnings,
            Errors = errors
        };
    }

    private static void CopyDirectory(string sourceDir, string destDir)
    {
        foreach (var file in Directory.GetFiles(sourceDir, "*", SearchOption.AllDirectories))
        {
            var relativePath = Path.GetRelativePath(sourceDir, file);
            var destPath = Path.Combine(destDir, relativePath);
            Directory.CreateDirectory(Path.GetDirectoryName(destPath)!);
            File.Copy(file, destPath, overwrite: true);
        }
    }

    private static void CopyDirectoryWithCollisionWarning(
        string sourceDir, string destDir, string themeName, Collection<string> warnings)
    {
        foreach (var file in Directory.GetFiles(sourceDir, "*", SearchOption.AllDirectories))
        {
            var relativePath = Path.GetRelativePath(sourceDir, file);
            var destPath = Path.Combine(destDir, relativePath);

            if (File.Exists(destPath))
                warnings.Add($"Asset '{relativePath}' in static/ overrides same file from theme '{themeName}'");

            Directory.CreateDirectory(Path.GetDirectoryName(destPath)!);
            File.Copy(file, destPath, overwrite: true);
        }
    }

    private static void CopyNonMarkdownFiles(string sourceDir, string destDir)
    {
        foreach (var file in Directory.GetFiles(sourceDir, "*", SearchOption.TopDirectoryOnly))
        {
            if (Path.GetExtension(file).Equals(".md", StringComparison.OrdinalIgnoreCase))
                continue;

            Directory.CreateDirectory(destDir);
            File.Copy(file, Path.Combine(destDir, Path.GetFileName(file)), overwrite: true);
        }
    }
}

