<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <StaticAnalysisCodeType>Test</StaticAnalysisCodeType>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.65.*" />
    <PackageReference Include="TUnit.Mocks" Version="1.65.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Kiln.Core\Kiln.Core.csproj" />
  </ItemGroup>

</Project>